pomegrate-mypro01/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pomegrate-mypro01/shopping/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'shopping'

urlpatterns = [
    path('', index, name='index'),
    path('profile/<int:pk>/', profile, name='profile'),
    path('profile/<int:pk>/order_list/', order_list, name='order_list'),
    path('order_info/<int:order_id>/', order_info, name='order_info'),
    path('notice/<int:pk>/', notice_detail, name='notice_detail'),
    path('show_category/<int:category_id>/', show_category, name='show_category'),
    path('detail/<int:pk>/', product_detail, name='product_detail'),
    path('cart_or_buy/<int:pk>/', cart_or_buy, name='cart_or_buy'),
    path('cart/<int:pk>/', cart, name='cart'),
    path('cart/<int:pk>/delete/', delete_cart, name='delete_cart'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='shop/index.html'), name='logout'),
    path('signup/', signup, name='signup'),
]

pomegrate-mypro01/shopping/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser


# Create your models here.
class Category(models.Model):
    sort = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.sort)

class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product_category')
    image = models.ImageField(upload_to='photos')
    price = models.IntegerField()
    price_text = models.TextField(default="")
    fabric = models.TextField(default="")
    size = models.TextField(default="")
    color = models.TextField(default="")
    quantity = models.IntegerField(default=99)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add = True)
    hit = models.IntegerField(default=0)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return '{}'.format(self.name)

class Point(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_point')
    all_point = models.IntegerField()
    able_point = models.IntegerField()

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wish_product', blank=True)
    
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return '{} // {}'.format(self.user, self.products.name)

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} by {}'.format(self.title, self.author)

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_order')
    name = models.CharField(max_length=100, verbose_name='주문자_이름')
    amount = models.PositiveIntegerField(verbose_name='결제금액', default="")
    home = models.CharField(max_length=100, verbose_name='배송지', default="")
    phone = models.CharField(max_length=100, verbose_name='연락처', default=00000000000)
    quantity = models.IntegerField(default=1)
    products = models.TextField(max_length=100, verbose_name='주문상품', default="")
    order_requset = models.TextField(default="")
    order_date = models.DateTimeField(auto_now_add=True)

    #모델 인스턴스를 아이디 값 내림차순 정렬
    class Meta:
        ordering = ('-order_date',)

    def __str__(self):
        return '{}의 주문 [{}]'.format(self.user, self.order_date)

class Image(models.Model):
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_image', blank=True)
    image = models.ImageField(upload_to='photos')
    order_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-products',)

    def  __str__(self):
        return '{}의 이미지 [{}]'.format(self.products, self.order_date)

pomegrate-mypro01/shopping/forms.py
from django import forms
from .models import Order


#
from django.contrib.auth.models import User
from django import forms

class SignUpForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    Repeat_password = forms.CharField(label='Repeat_password', widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ['username', 'password', 'first_name', 'last_name', 'email',]

    def clean_Repeat_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['Repeat_password']:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다')
        return cd['Repeat_password']

pomegrate-mypro01/shopping/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .models import Product, Post, Point, Order, Category, Cart, Image
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import SignUpForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth
from django.db.models import Sum
# Create your views here.

@csrf_exempt
def signup(request):
    if request.method == 'POST':
        if request.POST.get('password1') == request.POST.get('password2'):
            
            try:
                user = User.objects.create_user(username = request.POST.get('username'), password=request.POST.get('password1'))
                auth.login(request, user)
                return redirect('/')
            except:
                return render(request, 'account/signup.html')
    return render(request, 'account/signup.html')



        
def index(request):
    products = Product.objects.order_by('-pub_date')
    categories = Category.objects.all()
    context = {'products': products, 'categories': categories}

    return render(request, 'shop/index.html', context)

def profile(request, pk):
    user = User.objects.get(pk=pk)
    categories = Category.objects.all()
    orders = Order.objects.filter(user=user)
    
    context = {"user": user, "categories":  categories, 'orders':orders}
    return render(request, 'shop/profile.html', context)

def notice(request):
    post_list = Post.objects.all()
    categories = Category.objects.all()
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'categories': categories}
    return render(request, 'shop/notice.html', context)

def notice_detail(request, pk):
    categories = Category.objects.all()
    post = Post.objects.get(pk=pk)
    context = {"post": post, "categories":  categories}
    return render(request, 'shop/notice_detail.html', context)

def order_list(request, pk):
    categories = Category.objects.all()
    user = User.objects.get(pk=pk)
    cart = Cart.objects.filter(user=user)
    total_price = 3000
    for product in cart:
        for i in range(0,product.quantity):
            total_price += product.products.price
    cart_product = ""
    for product in cart:
        cart_product += "상품명 : " + product.products.name + "/ 갯수 : " +  str(product.quantity) + "\n"
     
    if request.method == 'POST':
        info = Order()
        info.user = user
        info.name = request.POST.get('name')
        info.amount = total_price
        info.home = request.POST.get('home')
        info.phone = request.POST.get('phone')
        info.order_requset = request.POST.get('order_requset')
        
        info.products = cart_product
        info.save()
        return redirect('/')
    
    context = {'user': user,  'categories': categories, 'total_price':total_price, 'cart':cart,}
    return render(request, 'shop/order_list.html', context)

def order_info(request, order_id):
    categories = Category.objects.all()
    order = Order.objects.all()
    order_info = Order.objects.get(pk=order_id)
    
    
    context = {  'categories': categories, 'order':order, 'order_info':order_info}
    return render(request, 'shop/order_info.html', context)

def show_category(request, category_id):
    categories = Category.objects.all()
    category = Category.objects.get(pk=category_id)
    products = Product.objects.filter(category=category).order_by('pub_date')
    lank_products = Product.objects.filter(category=category).order_by('-hit')[:4]
    paginator = Paginator(products, 5)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {'lank_products': lank_products, 'products': products, 'category': category, 'categories': categories}
    return render(request, 'shop/category.html', context)

def product_detail(request, pk):
    categories = Category.objects.all()
    product = Product.objects.get(pk=pk)
    category = Category.objects.get(pk=product.category.pk)
    Product.objects.filter(pk=pk).update(hit=product.hit+1)
    images = Image.objects.filter(products=product)
    point = int(product.price * 0.01)
    
    context = { "product": product, "point": point, "category": category, "categories": categories, 'images':images}
    return render(request, 'shop/detail.html', context)


def cart(request, pk):
    categories = Category.objects.all()
    user = User.objects.get(pk=pk)
    cart = Cart.objects.filter(user=user)
    total_price = 0
    for product in cart:
        for i in range(0,product.quantity):
            total_price += product.products.price
    paginator = Paginator(cart, 10)
    page = request.GET.get('page')
    total_price2 = total_price + 3000
    try:
        cart = paginator.page(page)
    except PageNotAnInteger:
        cart = paginator.page(1)
    except EmptyPage:
        cart = paginator.page(paginator.num_pages)
    context = {'user': user, 'cart': cart, 'categories': categories, 'total_price':total_price, 'total_price2':total_price2, }
    return render(request, 'shop/cart.html', context)

def delete_cart(request, pk):
    user = request.user
    cart = Cart.objects.filter(user=user)
    quantity = 0

    if request.method == 'POST':
        pk = int(request.POST.get('product'))
        product = Product.objects.get(pk=pk)
        for i in cart:
            if i.products == product :
                quantity =  i.quantity

        if quantity > 0 :
            product = Product.objects.filter(pk=pk)
            cart = Cart.objects.filter(user=user, products__in=product)
            cart.delete()
            return redirect('shopping:cart', user.pk)

@login_required
def cart_or_buy(request, pk):
    quantity = int(request.POST.get('quantity'))
    product = Product.objects.get(pk=pk)
    user = request.user
    categories = Category.objects.all()
    initial = {'name': product.name, 'amount': product.price, 'quantity': quantity}
    cart = Cart.objects.filter(user=user)
    if request.method == 'POST':
        if 'add_cart' in request.POST:
            for i in cart :
                if i.products == product:
                    product = Product.objects.filter(pk=pk)
                    Cart.objects.filter(user=user, products__in=product).update(quantity=F('quantity') + quantity)
                    messages.success(request,'장바구니 등록 완료')
                    return redirect('shopping:cart', user.pk)

            Cart.objects.create(user=user, products=product, quantity=quantity)
            messages.success(request, '장바구니 등록 완료')
            return redirect('shopping:cart', user.pk)

        elif 'buy' in request.POST:
            form = OrderForm(request.POST, initial=initial)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = user
                order.quantity = quantity
                order.products = product
                order.save()
                return redirect('shopping:order_list', user.pk)

            else:
                form = OrderForm(initial=initial)

            return render(request, 'shop/order_pay.html', {
                'form': form,
                'quantity': quantity,
                'iamport_shop_id': 'iamport',  # FIXME: 가맹점코드
                'user': user,
                'product': product,
                'categories': categories,
            })

pomegrate-mypro01/shopping/templates/shop/cart.html
{% extends "shop/../account/base.html" %}
{% load static %}
{% block title %}
MY CART
{% endblock title %}
<link rel="stylesheet" href="{% static 'shop/css/login.css' %}">
{% block content %}

<!-- Page Add Section Begin -->
<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>Cart<span>.</span></h2>


                </div>
            </div>
            <div class="col-lg-8">
                <img src="{% static 'shop/images/add.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->

<!-- Cart Page Section Begin -->
<div class="cart-page">
    <div class="container">
        <div class="cart-table">
            <table>
                <thead>
                    <tr>
                        <th class="product-h">Product</th>
                        <th>name</th>
                        <th>Price</th>
                        <th class="quan">Quantity</th>
                        <th></th>
                        
                        <th>delete</th>

                    </tr>
                </thead>

                {% if total_price == 0 %}
                <thead>
                    <tr>
                        <th class="product-h">***</th>
                        <th>빈장바구니</th>
                        <th>입니다.</th>
                        <th class="quan">***</th>
                        <th></th>
                        
                        <th></th>

                    </tr>
                </thead>
                {% else %}
                <form action="{% url 'shopping:delete_cart' user.pk %}" method="POST">
                    {% csrf_token %}
                    {% for product in cart %}
                    <thead>
                        <tr>
                            <th class="product-col">
                                <a>
                                    <img src="{{ product.products.image.url}}" alt="">
                                </a>
                            </th>
                            <th >
                                {{ product.products.name }}
                            </th>
                            <th >{{ product.products.price }}원</th>
                            <th >{{ product.quantity }}</th>

                            <th>
                                
                            </th>
                            <th >
                                <input type="hidden" id="product_{{ product.id }}" name="product"
                                    value="{{ product.products.id }}">
                                <button class="primary-btn chechout-btn">x</button>

                            </th>
                        </tr>
                    </thead>
                    {% endfor%}
                </form>
                {% endif %}

                </tbody>

            </table>

        </div>

    </div>
    <div class="cart-page">
        <div class="container">
            <div class="cart-table">
                <table>
                    <thead>
                        <tr>
                            <th >상풍가격</th>
                            <th></th>
                            <th>배송비</th>
                            <th></th>
                            <th >결제금액</th>
                            <th></th>
                            
    
                        </tr>
                    </thead>
                    <thead>
                        <tr>
                            <th >
                                {{ total_price}}
                            </th>
                            <th>
                                +
                            </th>
                            {% if total_price > 30000 %}
                            <th >
                                0
                            </th>
                            {% else %}
                            <th >
                                3000
                            </th>
                            {% endif %}
                            <th >=</th>
                            {% if total_price > 30000 %}
                            <th >
                                {{total_price}}
                            </th>
                            {% else %}
                            <th >
                                {{total_price2}}
                            </th>
                            {% endif %}
                            <th>
                                
                            </th>
                            <th >
                                <input type="hidden" id="product_{{ product.id }}" name="product"
                                    value="{{ product.id }}">
                                <a class="primary-btn chechout-btn" href="{% url 'shopping:order_list' user.pk %}">구매하기</a>

                            </th>
                        </tr>
                    </thead>
                      
    
                   
                </table>
    
            </div>
    
        </div>
        
    </div>
</div>
</div>
<!-- Cart Page Section End -->


{% endblock content %}

pomegrate-mypro01/shopping/templates/shop/category.html
{% extends "shop/../account/base.html" %}
{% load static %}
{% block title %}
    {{ category }}
{% endblock title %}

{% block content %}

    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>{{category.sort}}<span>.</span></h2>
                        <a href="{% url 'shopping:index' %}">Home</a>
                        <a href="#">{{category.sort}}</a>
                        
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'shop/images/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Categories Page Section Begin -->
    <section class="categories-page spad">
        <div class="container">
            <div class="categories-controls">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="categories-filter">
                            <div class="cf-left">
                                <form action="#">
                                    <select class="sort">
                                        <option value="">Sort by</option>
                                        <option value="">Orders</option>
                                        <option value="">Newest</option>
                                        <option value="">Price</option>
                                    </select>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                
                {% for product in products %}
                <div class="col-lg-3 col-md-6">
                    <div class="single-product-item">
                        <div class="product-text">
                            <a href="{% url 'shopping:product_detail' product.id %}">
                                <img src="{{ product.image.url }}" alt="" >
                            </a>                            
                            <p>5th Market</p>
                            
                        </div>
                        <div class="product-text">
                            <a href="{% url 'shopping:product_detail' product.id %}">
                                <p>{{ product.name }}</p>
                            </a>
                            <p>{{ product.price_text }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
            
        </div>
    </section>
    <!-- Categories Page Section End -->
{% endblock content %}

pomegrate-mypro01/shopping/templates/shop/detail.html
{% extends "shop/../account/base.html" %}

{% block title %}
DETAIL
{% endblock title %}
{% load static %}
{% block content %}
<!-- Page Add Section Begin -->
<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>{{category.sort}}<span>.</span></h2>
                    <a href="{% url 'shopping:index' %}">Home</a>
                    <a href="#">{{category.sort}}</a>

                </div>
            </div>
            <div class="col-lg-8">
                <img src="{% static 'shop/images/add.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->

<!-- Product Page Section Beign -->
<section class="product-page">
    <div class="container">
        
        <div class="row">
            <div class="col-lg-6">
                <div class="product-slider owl-carousel">
                    <div class="product-img">
                        <figure>
                            <img src="{{ product.image.url }}" alt="">
                            <div class="p-status">new</div>
                        </figure>
                    </div>
                    
                </div>

            </div>

            <div class="col-lg-6">
                <div class="product-content">
                    <h2>{{ product.name }}</h2>
                    <div class="pc-meta">
                        <h5>{{ product.price}}원</h5>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                    </div>
                    <p>{{ product.description}}</p>
                    <ul class="tags">
                        <li><span>Category :</span> {{product.category}}</li>
                        <li><span>Color :</span> {{ product.color }}</li>
                        <li><span>Size :</span> {{ product.size }}</li>
                    </ul>
                    {% csrf_token %}
                    <form action="{% url 'shopping:cart_or_buy' product.pk %}" , method="POST">
                        {% if user.is_authenticated %}
                        {% if product.quantity > 0 %}
                        <div class="product-quantity">
                            <div class="pro-qty">
                                <input type="text" value="1" name="quantity">
                            </div>
                        </div>
                        {% else %}
                        <a href="#" class="primary-btn pc-btn">SOLD OUT</a>
                        {% endif %}
                        
                        <button class="primary-btn pc-btn" type="submit" name="add_cart" value="add_cart">Add to
                            cart</button>
                        {%else%}
                        {%endif%}
                        {% csrf_token %}
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>
{% load disqus_tags %}
<section class="product-page">
    <div class="container">
        {% disqus_show_comments %}
    </div>
</section>
<section class="product-page">
    {% for a in images %}
    <div class="container">
        <div class="detail_img">
        <img class="detail_img" src="{{ a.image.url }}" alt="">
    </div>
    </div>
    {% endfor %}
</section>
<!-- Product Page Section End -->



{% endblock content %}

pomegrate-mypro01/shopping/templates/shop/header.html
{% load static%}


    <div class="logo-space col-md-12">
        <a href="{% url 'shopping:index' %}">
        <img src="{% static 'shop/images/main.png' %}"></a>
    </div>

pomegrate-mypro01/shopping/templates/shop/left_side.html
{% load static%}



<div class="side-top">
    <div class="account">
        <nav class="navbar navbar-light bg-light">
            {% if user.is_active %}
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopping:logout' %}">LOGOUT</a>
            </div>
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopping:profile' user.pk %}">MY PAGE</a>
            </div>
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopping:cart' user.pk %}">CART</a>
            </div>

            {% else %}
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopping:login' %}">LOGIN</a>
            </div>
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopping:signup' %}">SIGN UP</a>
            </div>

            {% endif %}
        </nav>
    </div>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'shopping:notice' %}">NOTICE</a>
        </div>
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Q&A</a>
        </div>
        <div class="container-fluid">
            <a class="navbar-brand" href="#">REVIEW</a>
        </div>
        <div class="container-fluid">
            <a class="navbar-brand" href="#">입고지연</a>
        </div>

    </nav>

</div>

<div class="side-category">
    <nav class="navbar navbar-light bg-light">
        {% for category in categories %}
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'shopping:show_category' category.pk %}">{{ category.sort }}</a>
        </div>
        {% endfor %}
        <div class="container-fluid">
            <a class="navbar-brand" href="#">SALE</a>
        </div>
    </nav>
</div>

pomegrate-mypro01/shopping/templates/shop/notice.html
{% extends "shop/../account/base.html" %}

{% block title %}
    NOTICE
{% endblock title %}

{% block content %}
    
    <div class="content">
        <div id="board_list">
            <div id="board_list_title">
                <div id="board_title">
                    <h2>
                        <span>NOTICE</span>
                    </h2>
                </div>
            </div>

            <div class="board_table">
                <table>
                    <thead>
                    <tr>
                        <th>no</th>
                        <th>제목</th>
                        <th>작성자</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for post in posts %}
                        <tr>
                            <td>{{ post.id }}</td>
                            <td><a href="{% url 'shop:notice_detail' post.pk %}">{{ post.title }}</a></td>
                            <td>{{ post.author }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- pagenation nav -->
        <div class="board_paging">
            <ol>
            {% if posts.has_previous %}
                <li class="paging_pre">
                    <a href="{% url 'shop:notice' %}?page={{ posts.previous_page_number }}"><</a>
                </li>
            {% endif %}

                <li><a href="#">{{ posts.number }}</a></li>

            {% if posts.has_next %}
                <li class="paging_next">
                    <a href="{% url 'shop:notice' %}?page={{ posts.next_page_number }}">></a>
                </li>
            {% endif %}
            </ol>
        </div>
    </div>
{% endblock content %}

pomegrate-mypro01/shopping/templates/shop/profile.html
{% extends "shop/../account/base.html" %}

{% block title %}
Profile
{% endblock title %}
{% load static %}
{% block content %}

<!-- Page Add Section Begin -->
<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>My Page<span>.</span></h2>


                </div>
            </div>
            <div class="col-lg-8">
                <img src="{% static 'shop/images/add.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->
<div class="cart-page">
    <div class="container">
        <div class="cart-table">
            <table>
                <thead>
                    <tr>
                        <th class="product-h">Username</th>
                        <th class="product-h">{{ user.username }}</th>               
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <th class="product-h">Order List</th>
                        <th class="product-h">{{ orders.order_date }}</th>               
                    </tr>
                    {% for order in orders %}
                    <tr>
                        <th class="product-h"></th>
                        <th class="product-h">
                            <a href="{% url 'shopping:order_info' order.id %}">주문일자 : {{ order.order_date }}/ 결제금액 : {{order.amount}}</a>
                        </th>               
                    </tr>
                    {% endfor %}
                </thead>
                <thead>
                    <tr>
                        <th class="product-h">My info</th>
                        <th class="product-h">{{ user.username }}</th>               
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <th class="product-h">My Cart</th>
                        <th class="product-h">
                            <a href="{% url 'shopping:cart' user.pk %}">
                                장바구니로 이동하기
                            </a></th>               
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>


{% endblock content %}

pomegrate-mypro01/shopping/templates/shop/sale.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>